# Generated by Django 5.2.13 on 2026-05-03 12:04

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "telegram_id",
                    models.BigIntegerField(
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="Telegram ID",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Username"
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="First Name"
                    ),
                ),
                (
                    "current_weight",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Текущий вес"
                    ),
                ),
                (
                    "target_weight",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Целевой вес"
                    ),
                ),
                (
                    "start_date",
                    models.DateField(auto_now_add=True, verbose_name="Дата начала"),
                ),
                (
                    "calculated_deadline",
                    models.DateField(
                        blank=True, null=True, verbose_name="Расчетный дедлайн"
                    ),
                ),
                (
                    "habit_fail_days",
                    models.IntegerField(
                        default=0, verbose_name="Дни провала привычек (сдвиг дедлайна)"
                    ),
                ),
                (
                    "notifications_enabled",
                    models.BooleanField(
                        default=True, verbose_name="Уведомления включены"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Пользователь",
                "verbose_name_plural": "Пользователи",
            },
        ),
        migrations.CreateModel(
            name="Stage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("target_weight", models.FloatField(verbose_name="Целевой вес этапа")),
                (
                    "is_achieved",
                    models.BooleanField(default=False, verbose_name="Достигнут"),
                ),
                (
                    "achieved_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата достижения"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stages",
                        to="bot_app.user",
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Этап (Микро-цель)",
                "verbose_name_plural": "Этапы",
                "ordering": ["-target_weight"],
            },
        ),
        migrations.CreateModel(
            name="MeasurementRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Дата записи"
                    ),
                ),
                (
                    "chest",
                    models.FloatField(blank=True, null=True, verbose_name="Грудь (см)"),
                ),
                (
                    "waist",
                    models.FloatField(blank=True, null=True, verbose_name="Талия (см)"),
                ),
                (
                    "hips",
                    models.FloatField(blank=True, null=True, verbose_name="Бедра (см)"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="measurements",
                        to="bot_app.user",
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Замеры тела",
                "verbose_name_plural": "Замеры тела",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="Habit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Название привычки"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активна"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="habits",
                        to="bot_app.user",
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Привычка",
                "verbose_name_plural": "Привычки",
            },
        ),
        migrations.CreateModel(
            name="WeightRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("weight", models.FloatField(verbose_name="Вес")),
                (
                    "date",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Дата записи"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="weight_records",
                        to="bot_app.user",
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Запись веса",
                "verbose_name_plural": "Записи веса",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="DailyHabitLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="Дата"
                    ),
                ),
                (
                    "is_completed",
                    models.BooleanField(default=False, verbose_name="Выполнено"),
                ),
                (
                    "habit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="bot_app.habit",
                        verbose_name="Привычка",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="habit_logs",
                        to="bot_app.user",
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Лог привычки",
                "verbose_name_plural": "Логи привычек",
                "unique_together": {("user", "habit", "date")},
            },
        ),
    ]
